/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppSearchRouteImport } from './routes/app/search'
import { Route as AppFriendsRouteImport } from './routes/app/friends'
import { Route as AppFeedRouteImport } from './routes/app/feed'
import { Route as AppWatchlistsIndexRouteImport } from './routes/app/watchlists/index'
import { Route as AppTrackerIndexRouteImport } from './routes/app/tracker.index'
import { Route as AppShuffleIndexRouteImport } from './routes/app/shuffle/index'
import { Route as AppWatchlistsWatchlistIdRouteImport } from './routes/app/watchlists/$watchlistId'
import { Route as AppShuffleHiddenRouteImport } from './routes/app/shuffle/hidden'
import { Route as AppSettingsBlockedRouteImport } from './routes/app/settings/blocked'
import { Route as AppProfileUserIdRouteImport } from './routes/app/profile.$userId'
import { Route as ApiUploadthingSplatRouteImport } from './routes/api/uploadthing/$'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiCronReviewRemindersRouteImport } from './routes/api/cron/review-reminders'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppTitleMediaTypeTmdbIdRouteImport } from './routes/app/title.$mediaType.$tmdbId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWatchlistsIndexRoute = AppWatchlistsIndexRouteImport.update({
  id: '/watchlists/',
  path: '/watchlists/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTrackerIndexRoute = AppTrackerIndexRouteImport.update({
  id: '/tracker/',
  path: '/tracker/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppShuffleIndexRoute = AppShuffleIndexRouteImport.update({
  id: '/shuffle/',
  path: '/shuffle/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWatchlistsWatchlistIdRoute =
  AppWatchlistsWatchlistIdRouteImport.update({
    id: '/watchlists/$watchlistId',
    path: '/watchlists/$watchlistId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppShuffleHiddenRoute = AppShuffleHiddenRouteImport.update({
  id: '/shuffle/hidden',
  path: '/shuffle/hidden',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsBlockedRoute = AppSettingsBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppProfileUserIdRoute = AppProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiUploadthingSplatRoute = ApiUploadthingSplatRouteImport.update({
  id: '/api/uploadthing/$',
  path: '/api/uploadthing/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronReviewRemindersRoute = ApiCronReviewRemindersRouteImport.update({
  id: '/api/cron/review-reminders',
  path: '/api/cron/review-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTitleMediaTypeTmdbIdRoute = AppTitleMediaTypeTmdbIdRouteImport.update({
  id: '/title/$mediaType/$tmdbId',
  path: '/title/$mediaType/$tmdbId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/feed': typeof AppFeedRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/onboarding/': typeof OnboardingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/review-reminders': typeof ApiCronReviewRemindersRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/uploadthing/$': typeof ApiUploadthingSplatRoute
  '/app/profile/$userId': typeof AppProfileUserIdRoute
  '/app/settings/blocked': typeof AppSettingsBlockedRoute
  '/app/shuffle/hidden': typeof AppShuffleHiddenRoute
  '/app/watchlists/$watchlistId': typeof AppWatchlistsWatchlistIdRoute
  '/app/shuffle/': typeof AppShuffleIndexRoute
  '/app/tracker/': typeof AppTrackerIndexRoute
  '/app/watchlists/': typeof AppWatchlistsIndexRoute
  '/app/title/$mediaType/$tmdbId': typeof AppTitleMediaTypeTmdbIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/feed': typeof AppFeedRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/onboarding': typeof OnboardingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/review-reminders': typeof ApiCronReviewRemindersRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/uploadthing/$': typeof ApiUploadthingSplatRoute
  '/app/profile/$userId': typeof AppProfileUserIdRoute
  '/app/settings/blocked': typeof AppSettingsBlockedRoute
  '/app/shuffle/hidden': typeof AppShuffleHiddenRoute
  '/app/watchlists/$watchlistId': typeof AppWatchlistsWatchlistIdRoute
  '/app/shuffle': typeof AppShuffleIndexRoute
  '/app/tracker': typeof AppTrackerIndexRoute
  '/app/watchlists': typeof AppWatchlistsIndexRoute
  '/app/title/$mediaType/$tmdbId': typeof AppTitleMediaTypeTmdbIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/feed': typeof AppFeedRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/onboarding/': typeof OnboardingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/review-reminders': typeof ApiCronReviewRemindersRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/uploadthing/$': typeof ApiUploadthingSplatRoute
  '/app/profile/$userId': typeof AppProfileUserIdRoute
  '/app/settings/blocked': typeof AppSettingsBlockedRoute
  '/app/shuffle/hidden': typeof AppShuffleHiddenRoute
  '/app/watchlists/$watchlistId': typeof AppWatchlistsWatchlistIdRoute
  '/app/shuffle/': typeof AppShuffleIndexRoute
  '/app/tracker/': typeof AppTrackerIndexRoute
  '/app/watchlists/': typeof AppWatchlistsIndexRoute
  '/app/title/$mediaType/$tmdbId': typeof AppTitleMediaTypeTmdbIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/login'
    | '/app/feed'
    | '/app/friends'
    | '/app/search'
    | '/app/settings'
    | '/onboarding/'
    | '/api/auth/$'
    | '/api/cron/review-reminders'
    | '/api/trpc/$'
    | '/api/uploadthing/$'
    | '/app/profile/$userId'
    | '/app/settings/blocked'
    | '/app/shuffle/hidden'
    | '/app/watchlists/$watchlistId'
    | '/app/shuffle/'
    | '/app/tracker/'
    | '/app/watchlists/'
    | '/app/title/$mediaType/$tmdbId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/feed'
    | '/app/friends'
    | '/app/search'
    | '/app/settings'
    | '/onboarding'
    | '/api/auth/$'
    | '/api/cron/review-reminders'
    | '/api/trpc/$'
    | '/api/uploadthing/$'
    | '/app/profile/$userId'
    | '/app/settings/blocked'
    | '/app/shuffle/hidden'
    | '/app/watchlists/$watchlistId'
    | '/app/shuffle'
    | '/app/tracker'
    | '/app/watchlists'
    | '/app/title/$mediaType/$tmdbId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/login'
    | '/app/feed'
    | '/app/friends'
    | '/app/search'
    | '/app/settings'
    | '/onboarding/'
    | '/api/auth/$'
    | '/api/cron/review-reminders'
    | '/api/trpc/$'
    | '/api/uploadthing/$'
    | '/app/profile/$userId'
    | '/app/settings/blocked'
    | '/app/shuffle/hidden'
    | '/app/watchlists/$watchlistId'
    | '/app/shuffle/'
    | '/app/tracker/'
    | '/app/watchlists/'
    | '/app/title/$mediaType/$tmdbId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronReviewRemindersRoute: typeof ApiCronReviewRemindersRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiUploadthingSplatRoute: typeof ApiUploadthingSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/friends': {
      id: '/app/friends'
      path: '/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/feed': {
      id: '/app/feed'
      path: '/feed'
      fullPath: '/app/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/watchlists/': {
      id: '/app/watchlists/'
      path: '/watchlists'
      fullPath: '/app/watchlists/'
      preLoaderRoute: typeof AppWatchlistsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tracker/': {
      id: '/app/tracker/'
      path: '/tracker'
      fullPath: '/app/tracker/'
      preLoaderRoute: typeof AppTrackerIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/shuffle/': {
      id: '/app/shuffle/'
      path: '/shuffle'
      fullPath: '/app/shuffle/'
      preLoaderRoute: typeof AppShuffleIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/watchlists/$watchlistId': {
      id: '/app/watchlists/$watchlistId'
      path: '/watchlists/$watchlistId'
      fullPath: '/app/watchlists/$watchlistId'
      preLoaderRoute: typeof AppWatchlistsWatchlistIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/shuffle/hidden': {
      id: '/app/shuffle/hidden'
      path: '/shuffle/hidden'
      fullPath: '/app/shuffle/hidden'
      preLoaderRoute: typeof AppShuffleHiddenRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/blocked': {
      id: '/app/settings/blocked'
      path: '/blocked'
      fullPath: '/app/settings/blocked'
      preLoaderRoute: typeof AppSettingsBlockedRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/profile/$userId': {
      id: '/app/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/app/profile/$userId'
      preLoaderRoute: typeof AppProfileUserIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/uploadthing/$': {
      id: '/api/uploadthing/$'
      path: '/api/uploadthing/$'
      fullPath: '/api/uploadthing/$'
      preLoaderRoute: typeof ApiUploadthingSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/review-reminders': {
      id: '/api/cron/review-reminders'
      path: '/api/cron/review-reminders'
      fullPath: '/api/cron/review-reminders'
      preLoaderRoute: typeof ApiCronReviewRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/title/$mediaType/$tmdbId': {
      id: '/app/title/$mediaType/$tmdbId'
      path: '/title/$mediaType/$tmdbId'
      fullPath: '/app/title/$mediaType/$tmdbId'
      preLoaderRoute: typeof AppTitleMediaTypeTmdbIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsBlockedRoute: typeof AppSettingsBlockedRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsBlockedRoute: AppSettingsBlockedRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteRouteChildren {
  AppFeedRoute: typeof AppFeedRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppProfileUserIdRoute: typeof AppProfileUserIdRoute
  AppShuffleHiddenRoute: typeof AppShuffleHiddenRoute
  AppWatchlistsWatchlistIdRoute: typeof AppWatchlistsWatchlistIdRoute
  AppShuffleIndexRoute: typeof AppShuffleIndexRoute
  AppTrackerIndexRoute: typeof AppTrackerIndexRoute
  AppWatchlistsIndexRoute: typeof AppWatchlistsIndexRoute
  AppTitleMediaTypeTmdbIdRoute: typeof AppTitleMediaTypeTmdbIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppFeedRoute: AppFeedRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppProfileUserIdRoute: AppProfileUserIdRoute,
  AppShuffleHiddenRoute: AppShuffleHiddenRoute,
  AppWatchlistsWatchlistIdRoute: AppWatchlistsWatchlistIdRoute,
  AppShuffleIndexRoute: AppShuffleIndexRoute,
  AppTrackerIndexRoute: AppTrackerIndexRoute,
  AppWatchlistsIndexRoute: AppWatchlistsIndexRoute,
  AppTitleMediaTypeTmdbIdRoute: AppTitleMediaTypeTmdbIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronReviewRemindersRoute: ApiCronReviewRemindersRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiUploadthingSplatRoute: ApiUploadthingSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
